export const ADD_FEATURE = "ADD_FEATURE";

// Enabled features
export const FETCH_ENABLED_FEATURES = "FETCH_ENABLED_FEATURES";
export const FETCH_ALL_FEATURES = "FETCH_ALL_FEATURES";

/* Toggling modules and features */
export const TOGGLE_FEATURE_STATE = "TOGGLE_FEATURE_STATE";
export const TOGGLE_MODULE_STATE = "TOGGLE_MODULE_STATE";

// Social icons
export const FETCH_ALL_SOCIAL_ICONS = "FETCH_ALL_SOCIAL_ICONS";

// SEO details
export const FETCH_PROJECT_DETAIL = "FETCH_PROJECT_DETAIL";
export const UPDATE_PROJECT_DETAIL = "UPDATE_PROJECT_DETAIL";
export const FETCH_OWNER_INFO_DETAIL = "FETCH_OWNER_INFO_DETAIL";

// Update project name
export const UPDATE_PROJECT_NAME = "UPDATE_PROJECT_NAME";

// Change field like company name, dic, ico etc. (without persisting the changes)
export const CHANGE_OWNER_INFO_FIELD = "CHANGE_OWNER_INFO_FIELD";
//  Save owner info changes into database
export const UPDATE_OWNER_INFO_FIELD = "UPDATE_OWNER_INFO_FIELD";

// Get all thmes for admin setup
export const FETCH_ALL_THEMES = "FETCH_ALL_THEMES";

// Update project theme
export const UPDATE_PROJECT_THEME = "UPDATE_PROJECT_THEME";

// Articles fetching
export const FETCH_ALL_ARTICLES = "FETCH_ALL_ARTICLES";
export const FETCH_RECENT_ARTICLES = "FETCH_RECENT_ARTICLES";

// Articles fetching with pagination
export const FETCH_PAGGED_ARTICLES = "FETCH_PAGED_ARTICLES";



export const FETCH_ARTICLES_PAGE_COUNT = "FETCH_ARTICLES_PAGE_COUNT";

// Articles categories fetching
export const FETCH_ALL_ARTICLE_CATEGORIES = "FETCH_ALL_ARTICLE_CATEGORIES";

// Single article fetching
export const FETCH_ARTICLE_BY_ID = "FETCH_ARTICLE_BY_ID";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
// Reset actual article detail
export const RESET_ACTUAL_ARTICLE = "RESET_ACTUAL_ARTICLE";

// Update article details
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";

// Modules loading
export const FETCH_HEADER_MODULES = "FETCH_HEADER_MODULES";
export const FETCH_BODY_MODULES = "FETCH_BODY_MODULES";
export const FETCH_FOOTER_MODULES = "FETCH_FOOTER_MODULES";

export const MUTATE_MODULES_FEATURES = "MUTATE_MODULES_FEATURES";

export const FETCH_ENABLED_MODULES = "FETCH_ENABLED_MODULES";

export const FETCH_PAGGED_MODULE_FEATURES = "FETCH_PAGGED_MODULE_FEATURES";

export const IS_USER_AUTHENTICATED = "IS_USER_AUTHENTICATED";

// lOGIN ACTION
export const AUTHENTICATE = "AUTHENTICATE";

// USER SIGN OUT
export const USER_SIGN_OUT = "USER_SIGN_OUT";

export const CORRECT_GUESS = "CORRECT_GUESS";

/* ====  SUMMARY STATS ==== */

// fetch dashboard summary stats
export const FETCH_DASHBOARD_SUMMARY_STATS = "FETCH_DASHBOARD_SUMMARY_STATS";

/* ==== NEWSLETTER INFO === */
export const NEWSLETTER_CHANGE_EMAIL = "NEWSLETTER_CHANGE_EMAIL";
export const NEWSLETTER_RESET_CREDENTIALS = "NEWSLETTER_RESET_CREDENTIALS";

/* === WRITE TO US MODULE === */
export const WRITE_TO_US_TOGGLE_MODAL = "WRITE_TO_US_TOGGLE_MODAL";
export const WRITE_TO_US_CHANGE_FIELD = "WRITE_TO_US_CHANGE_FIELD";
export const WRITE_TO_US_RESET_ALL_FIELDS = "WRITE_TO_US_RESET_ALL_FIELDS";

/* === RECOMMEND US MODULE === */

export const RECOMMEND_US_TOGGLE_MODAL = "RECOMMEND_US_TOGGLE_MODAL";
export const RECOMMEND_US_CHANGE_FIELD = "RECOMMEND_US_CHANGE_FIELD";
export const RECOMMEND_US_RESET_ALL_FIELDS = "RECOMMEND_US_RESET_ALL_FIELDS";

/* === NOTIFICATION SYSTEM === */
export const SET_CURRENT_NOTIFICATION = "SET_CURRENT_NOTIFICATION";
export const TOGGLE_NOTIFICATION_VISIBILITY = "TOGGLE_NOTIFICATION_VISIBILITY";
export const TURN_OFF_NOTIFICATION_VISIBILITY =
  "TURN_OFF_NOTIFICATION_VISIBILITY";

/* === GALLERY SYSTEM */
export const FETCH_ALL_IMAGES = "FETCH_ALL_IMAGES";
export const GALLERY_SYSTEM_NEW_IMAGE = "GALLERY_SYSTEM_NEW_IMAGE";
export const GALLERY_SYSTEM_DELETE_IMAGE = "GALLERY_SYSTEM_DELETE_IMAGE";
