import React from "react";

import styled from "styled-components";

/* Type checking. */
import IEventHandlerHTMLElement from "../../../../typescript/interfaces/shared/event-handlers/IEvent-Handler-Html-Element";
import IStyledComponentProps from "../../../../typescript/interfaces/shared/styled-components/IStyled-React-Component-Props";
import { Input } from "reactstrap";

/**
 * @interface IProps => Components props interface.
 */
interface IProps extends IStyledComponentProps {
  inputId: string;

  onChange(event: IEventHandlerHTMLElement): void | null;
}

/**
 * @function InputFile => Common shared component that represents file input field.
 * @param className => Class name that has beeen generated by "Styled Components" JS library.
 * @param inputId => String identifier od input field.
 * @param onChange => Functionality for onChange event.
 */
const InputFile: React.FC<IProps> = ({ className, inputId, onChange }) => {
  return (
    <Input
      className={className}
      data-title="aa"
      id={inputId}
      onChange={onChange}
      type="file"
    />
  );
};

export default styled(InputFile)`
  background: red;
`;
